services:

  grpc_service:
    build: .
    depends_on:
      - db
  
    networks:
      - share-net
    
    environment:
      POSTGRES_DATABASE: test_db
      POSTGRES_USERNAME: test_user
      POSTGRES_PASSWORD: test_pass
      ADMIN_USERNAME: test_admin
      ADMIN_PASSWORD: test_admin_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      GRPC_PORT: 3333

    command: ["python", "main.py"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    networks:
      - share-net

    # healthcheck:
    #   test: [CMD-SHELL", "pg_isready"]
    #     interval: "1s"
    #   timeout: "5s"
    #     retries: 10

networks:
  share-net:
    external: true