services:

  grpc:
    build: .
    depends_on:
      - db
  
    networks:
      - net
    
    environment:
      POSTGRES_DATABASE: db_wy
      POSTGRES_USERNAME: wyvern
      POSTGRES_PASSWORD: testpass
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      GRPC_PORT: 3333

    command: ["python", "main.py"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: wyvern
      POSTGRES_DB: db_wy
    networks:
      - net

    # healthcheck:
    #   test: [CMD-SHELL", "pg_isready"]
    #     interval: "1s"
    #   timeout: "5s"
    #     retries: 10

networks:
  net:
    driver: bridge